REM
REM Load a BitMap from an IFF ILBM file
REM

OPTION EXPLICIT
IMPORT IFFSupport

SCREEN 1, 320, 200, 5, 0, "ILBM BitMap Demo"
WINDOW 1, ,(0,0)-(320,200), _
AW_FLAG_BACKDROP OR AW_FLAG_SIMPLE_REFRESH OR AW_FLAG_BORDERLESS OR AW_FLAG_ACTIVATE, 1

DIM AS BITMAP_t PTR dragon = NULL

ILBM LOAD BITMAP "PROGDIR:imgs/dragon.iff", dragon, 1


PUT (10, 20), dragon
PUT (160, 50), dragon

REM WAIT FOR MOUSE BUTTON

SUB doQuit
    SYSTEM
END SUB
ON MOUSE CALL doQuit
MOUSE ON

WHILE TRUE
    SLEEP
WEND

