OPTION EXPLICIT

IMPORT OSGadTools

CONST AE_GTG_CREATE   AS INTEGER = 400
CONST AE_GTG_MODIFY   AS INTEGER = 401
CONST AE_GTG_DEPLOY   AS INTEGER = 402
CONST AE_GTG_SELECTED AS INTEGER = 403
CONST AE_GTG_CALLBACK AS INTEGER = 404
CONST AE_GTG_BUFFER   AS INTEGER = 405
CONST AE_GTG_NUM      AS INTEGER = 406

TYPE GTGADGET

    PUBLIC:

        DECLARE CONSTRUCTOR (BYVAL txt AS STRING, _
                             _COORD2(BYVAL s1 AS BOOLEAN, BYVAL x1 AS INTEGER, BYVAL y1 AS INTEGER, BYVAL s2 AS BOOLEAN, BYVAL x2 AS INTEGER, BYVAL y2 AS INTEGER), _
                             BYVAL user_data AS VOID PTR=NULL, BYVAL flags AS ULONG=0, BYVAL underscore AS ULONG=95)

        DECLARE PROPERTY x1 AS INTEGER
        DECLARE PROPERTY x1 (BYVAL x AS INTEGER)

        DECLARE PROPERTY y1 AS INTEGER
        DECLARE PROPERTY y1 (BYVAL y AS INTEGER)

        DECLARE PROPERTY x2 AS INTEGER
        DECLARE PROPERTY x2 (BYVAL x AS INTEGER)

        DECLARE PROPERTY y2 AS INTEGER
        DECLARE PROPERTY y2 (BYVAL y AS INTEGER)

        DECLARE PROPERTY text AS STRING
        DECLARE PROPERTY text (BYVAL txt AS STRING)

        DECLARE PROPERTY id AS INTEGER
        DECLARE PROPERTY id (BYVAL id AS INTEGER)

        DECLARE PROPERTY flags AS ULONG
        DECLARE PROPERTY flags (BYVAL f AS ULONG)

        DECLARE PROPERTY deployed AS BOOLEAN

        AS SUB (BYVAL GTGADGET PTR, BYVAL UINTEGER) gadgetup_cb
        AS SUB (BYVAL GTGADGET PTR, BYVAL UINTEGER) gadgetdown_cb
        AS SUB (BYVAL GTGADGET PTR, BYVAL UINTEGER) gadgetmove_cb

        AS VOID PTR user_data
        AS ULONG    underscore

    PRIVATE:

        AS GTGADGET PTR   prev, next

        AS NewGadget      ng

        AS Gadget PTR     gad
        AS Window PTR     win

        AS VOID PTR       deploy_cb


END TYPE

TYPE GTBUTTON EXTENDS GTGADGET

    PUBLIC:
       DECLARE CONSTRUCTOR (BYVAL txt AS STRING, _
                            _COORD2(BYVAL s1 AS BOOLEAN=FALSE, BYVAL x1 AS INTEGER, BYVAL y1 AS INTEGER, BYVAL s2 AS BOOLEAN=FALSE, BYVAL x2 AS INTEGER, BYVAL y2 AS INTEGER), _
                            BYVAL user_data AS VOID PTR=NULL, BYVAL flags AS ULONG=0, BYVAL underscore AS ULONG=95)

       DECLARE PROPERTY disabled AS BOOLEAN
       DECLARE PROPERTY disabled (BYVAL b AS BOOLEAN)

    PRIVATE:
        AS BOOLEAN  _disabled

END TYPE

TYPE GTCHECKBOX EXTENDS GTGADGET

    PUBLIC:
        DECLARE CONSTRUCTOR (BYVAL txt AS STRING, _
                             _COORD2(BYVAL s1 AS BOOLEAN=FALSE, BYVAL x1 AS INTEGER, BYVAL y1 AS INTEGER, BYVAL s2 AS BOOLEAN=FALSE, BYVAL x2 AS INTEGER, BYVAL y2 AS INTEGER), _
                             BYVAL user_data AS VOID PTR=NULL, BYVAL flags AS ULONG=0, BYVAL underscore AS ULONG=95)

        DECLARE PROPERTY disabled AS BOOLEAN
        DECLARE PROPERTY disabled (BYVAL b AS BOOLEAN)

        DECLARE PROPERTY checked AS BOOLEAN
        DECLARE PROPERTY checked (BYVAL b AS BOOLEAN)

    PRIVATE:
        AS BOOLEAN  _disabled
        AS BOOLEAN  _checked

END TYPE

TYPE GTSLIDER EXTENDS GTGADGET

    PUBLIC:

        DECLARE CONSTRUCTOR (BYVAL min AS INTEGER, BYVAL max AS INTEGER, BYVAL level AS INTEGER, BYVAL freedom AS ULONG, _
                             _COORD2(BYVAL s1 AS BOOLEAN=FALSE, BYVAL x1 AS INTEGER, BYVAL y1 AS INTEGER, BYVAL s2 AS BOOLEAN=FALSE, BYVAL x2 AS INTEGER, BYVAL y2 AS INTEGER), _
                             BYVAL user_data AS VOID PTR=NULL, BYVAL flags AS ULONG=0, BYVAL underscore AS ULONG=95)

        DECLARE PROPERTY disabled AS BOOLEAN
        DECLARE PROPERTY disabled (BYVAL b AS BOOLEAN)

        DECLARE PROPERTY min AS INTEGER
        DECLARE PROPERTY min (BYVAL i AS INTEGER)

        DECLARE PROPERTY max AS INTEGER
        DECLARE PROPERTY max (BYVAL i AS INTEGER)

        DECLARE PROPERTY level AS INTEGER
        DECLARE PROPERTY level (BYVAL i AS INTEGER)

        DECLARE PROPERTY maxLevelLen AS INTEGER
        DECLARE PROPERTY maxLevelLen (BYVAL i AS INTEGER)

        DECLARE PROPERTY levelFormat AS STRING
        DECLARE PROPERTY levelFormat (BYVAL s AS STRING)

        DECLARE PROPERTY levelPlace AS ULONG
        DECLARE PROPERTY levelPlace (BYVAL u AS ULONG)

        DECLARE PROPERTY immediate AS BOOLEAN
        DECLARE PROPERTY immediate (BYVAL b AS BOOLEAN)

        DECLARE PROPERTY relVerify AS BOOLEAN
        DECLARE PROPERTY relVerify (BYVAL b AS BOOLEAN)

        DECLARE PROPERTY freedom AS ULONG
        DECLARE PROPERTY freedom (BYVAL u AS ULONG)

    PRIVATE:
        AS BOOLEAN  _disabled
        AS INTEGER  _min, _max, _level
        AS ULONG    _freedom
        AS INTEGER  _maxLevelLen
        AS STRING   _levelFormat
        AS ULONG    _levelPlace
        AS BOOLEAN  _immediate, _relVerify

END TYPE

DECLARE SUB      GTGADGETS DEPLOY
DECLARE SUB      GTGADGETS FREE

DECLARE SUB      GTG DRAW BEVEL BOX (_COORD2(BYVAL s1 AS BOOLEAN=FALSE, BYVAL x1 AS INTEGER, BYVAL y1 AS INTEGER, BYVAL s2 AS BOOLEAN=FALSE, BYVAL x2 AS INTEGER, BYVAL y2 AS INTEGER), BYVAL recessed AS BOOLEAN = FALSE)

DECLARE FUNCTION GTGADGETS_NEXT_ID AS INTEGER

