OPTION EXPLICIT

IMPORT OSGadTools

CONST AE_GTG_CREATE   AS INTEGER = 400
CONST AE_GTG_MODIFY   AS INTEGER = 401
CONST AE_GTG_DEPLOY   AS INTEGER = 402
CONST AE_GTG_SELECTED AS INTEGER = 403
CONST AE_GTG_CALLBACK AS INTEGER = 404
CONST AE_GTG_BUFFER   AS INTEGER = 405
CONST AE_GTG_NUM      AS INTEGER = 406

TYPE GTGADGET_t
    AS GTGADGET_t PTR prev, next
    AS INTEGER        id
    AS Gadget PTR     gad
    AS Window PTR     win
    AS SUB (BYVAL INTEGER, BYVAL INTEGER, BYVAL UINTEGER, BYVAL VOID PTR) gadgetup_cb
    AS SUB (BYVAL INTEGER, BYVAL INTEGER, BYVAL UINTEGER, BYVAL VOID PTR) gadgetdown_cb
END TYPE

DECLARE FUNCTION GTGADGET (BYVAL kind AS INTEGER, _
                           _COORD2(BYVAL s1 AS BOOLEAN=FALSE, BYVAL x1 AS INTEGER, BYVAL y1 AS INTEGER, BYVAL s2 AS BOOLEAN=FALSE, BYVAL x2 AS INTEGER, BYVAL y2 AS INTEGER), _
                           BYVAL txt AS STRING, BYVAL flags AS ULONG, BYVAL id AS INTEGER, BYVAL tag AS ULONG, ...) AS GTGADGET_t PTR


DECLARE SUB      GTG MODIFY  (BYVAL g AS GTGADGET_t PTR, BYVAL tag AS ULONG, ...)

DECLARE FUNCTION GTGSELECTED (BYVAL g AS GTGADGET_t PTR) AS BOOLEAN
DECLARE FUNCTION GTGBUFFER   (BYVAL g AS GTGADGET_t PTR) AS STRING
DECLARE FUNCTION GTGNUM      (BYVAL g AS GTGADGET_t PTR) AS LONG

DECLARE SUB      GTGADGETS DEPLOY
DECLARE SUB      GTGADGETS FREE

DECLARE SUB      ON GTG UP   CALL (BYVAL g AS GTGADGET_t PTR, BYVAL cb AS SUB (BYVAL INTEGER, BYVAL INTEGER, BYVAL UINTEGER, BYVAL VOID PTR), BYVAL ud AS VOID PTR)
DECLARE SUB      ON GTG DOWN CALL (BYVAL g AS GTGADGET_t PTR, BYVAL cb AS SUB (BYVAL INTEGER, BYVAL INTEGER, BYVAL UINTEGER, BYVAL VOID PTR), BYVAL ud AS VOID PTR)
DECLARE SUB      ON GTG MOVE CALL (BYVAL g AS GTGADGET_t PTR, BYVAL cb AS SUB (BYVAL INTEGER, BYVAL INTEGER, BYVAL UINTEGER, BYVAL VOID PTR), BYVAL ud AS VOID PTR)

