REM test UCASE$, LCASE$, LEFT$, RIGHT$, INSTR

OPTION EXPLICIT

DIM AS STRING s="abcdABCD1234abcd"

DIM AS STRING s1=UCASE$(s)
'TRACE s1
ASSERT s1="ABCDABCD1234ABCD"

DIM AS STRING s2=LCASE$(s)
'TRACE s2
ASSERT s2="abcdabcd1234abcd"

DIM AS STRING s3=LEFT$(s,4)
'TRACE s3
ASSERT s3="abcd"

DIM AS STRING s4=RIGHT$(s,8)
'TRACE s4
ASSERT s4="1234abcd"

ASSERT INSTR (,s,"ABCD")=5
ASSERT INSTR (5,s,"abcd")=13
ASSERT INSTR (,s,"xyz")=0

