OPTION EXPLICIT

IMPORT OSGadToolsConsts

CONST AE_GTGADGET_CREATE AS INTEGER = 400
CONST AE_GTGADGET_DEPLOY AS INTEGER = 401

TYPE GTGADGET_t
    AS GTGADGET_t PTR prev, next
    AS INTEGER        id
END TYPE

DECLARE FUNCTION GTGADGET (BYVAL kind AS INTEGER, _
                           _COORD2(BYVAL s1 AS BOOLEAN=FALSE, BYVAL x1 AS INTEGER, BYVAL y1 AS INTEGER, BYVAL s2 AS BOOLEAN=FALSE, BYVAL x2 AS INTEGER, BYVAL y2 AS INTEGER), _
                           BYVAL txt AS STRING, BYVAL flags AS ULONG, BYVAL id AS INTEGER, ...) AS GTGADGET_t PTR

DECLARE SUB GTGADGETS DEPLOY

DECLARE SUB GTGADGETS FREE

DECLARE SUB ON GTGADGETUP CALL (BYVAL g AS GTGADGET_t PTR, BYVAL cb AS SUB (BYVAL INTEGER, BYVAL INTEGER, BYVAL GTGADGET_t PTR))

