= AQB Reference
Guenter Bartsch <guenter@zamia.org>
v0.1, 2020-07-12
:toc:

== Core Language

=== ASSERT

Syntax:

    ASSERT expr

raise an error message including line number information if the given expression evaluates to FALSE.

=== ACOS()

Syntax:

    ACOS "(" a ")"

obtain the arccosine of the floating point number

=== ASIN()

Syntax:

    ASIN "(" a ")"

obtain the arcsine of the floating point number

=== ATN()

Syntax:

    ATN "(" a ")"

obtain the arctangent of the floating point number

=== CAST()

Syntax:

    CAST "(" typedesc "," expr ")

casts an expression to a different data type

=== CHR$()

Syntax:

    CHR$ "(" expr ")"

returns a string containing the single character associated with the given character code

=== CONST

Syntax A:

    [ PUBLIC | PRIVATE ] CONST id1 [AS type] "=" expr [ "," id2 [AS type] "=" expr [ "," ...]]

Syntax B:

    [ PUBLIC | PRIVATE ] CONST AS type id1 "=" expr [ "," id2 "=" expr [ "," ...]]

declare constants

=== COS()

Syntax:

    COS "(" a ")"

obtain the cosine of the floating point number

=== DEFINT

Syntax:

    DEFINT letter [ "-" letter ] ( "," letter [ "-" letter ] )*

define all variables with names starting with the specified letter (or letter range) as INTEGER

=== DEFLNG

Syntax:

    DEFLNG letter [ "-" letter ] ( "," letter [ "-" letter ] )*

define all variables with names starting with the specified letter (or letter range) as LONG

=== DEFSNG

Syntax:

    DEFSNG letter [ "-" letter ] ( "," letter [ "-" letter ] )*

define all variables with names starting with the specified letter (or letter range) as SINGLE

=== DEFSTR

Syntax:

    DEFSTR letter [ "-" letter ] ( "," letter [ "-" letter ] )*

define all variables with names starting with the specified letter (or letter range) as STRING

=== DIM

Syntax A:

    [ PUBLIC | PRIVATE ] DIM [ SHARED ] var1 AS type [ "=" expr ] [ "," var2 AS ...]

Syntax B:

    [ PUBLIC | PRIVATE ] DIM [ SHARED ] AS type var1 [ "=" expr ] [ "," var2 ... ]

declare variables

=== EXIT

Syntax:

    EXIT ( SUB | FUNCTION | DO | FOR | WHILE | SELECT ) [ "," ( SUB | ... ) ... ]

exits a DO, WHILE or FOR loop, a FUNCTION or a SUB procedure, or a SELECT statement.

=== EXP()

Syntax:

    EXP "(" a ")"

obtain the exponential of the floating point number

=== FOR ... NEXT

Syntax:

    FOR id [ AS type ] "=" expr TO expr [ STEP expr ]
        <code>
    NEXT [ id1 [ "," id2 [ "," ...] ] ]

counter loop using specified start and stop numerical boundaries, default increment is 1

=== GOTO

Syntax:

    GOTO ( num | ident )

jump a line label or a line number in the program

=== IMPORT

Syntax:

    IMPORT id

import a module

=== LOG()

Syntax:

    LOG "(" l ")"

obtain the natural logarithm of the floating point number

=== OPTION EXPLICIT

Syntax:

    OPTION EXPLICIT [ ( ON | OFF ) ]

instructs the compiler to require variable declaration

=== OPTION PRIVATE

Syntax:

    OPTION PRIVATE [ ( ON | OFF ) ]

make declared variables, types, functions and subprograms private (not exported) by default

=== SIN()

Syntax:

    SIN "(" a ")

obtain the sine of the floating point number

=== SIZEOF()

Syntax:

    SIZEOF "(" ident ")

Returns the memory size in bytes of a given variable or named type

=== SQR()

Syntax:

    SQR "(" x ")"

obtain the square root of the floating point number

=== STATIC

Syntax A:

    STATIC Identifier AS TypeIdentifier [ "(" arrayDimensions ")" ] [ "=" expr] ( "," Indetifier2 AS ... )*

Syntax B:

    STATIC AS TypeIdentifier [ "(" arrayDimensions ")" ] Identifier [ "=" expr] ( "," Identifier2 ... )*

declare variable(s) as static.

=== STR$()

Syntax:

    STR$ "(" expr ")"

return a string representation (the same one that is used in PRINT output) of a given numeric expression

=== TAN()

Syntax:

    TAN "(" a ")"

obtain the tangent of the floating point number

=== WHILE ... WEND

Syntax:

    WHILE expression
        <code>
    WEND

repeat loop body while expression evaluates to TRUE

== AQB / AmigaBASIC

=== CSRLIN()

Syntax:

    CSRLIN "(" ")"

returns the current text row position

=== INKEY$()

Syntax:

    INKEY$ "(" ")"

returns a character entered from the keyboard

=== LINE

Syntax:

    LINE [[STEP] "(" x1 "," y1 ")" ] "-" [STEP] "(" x2 "," y2 ")" [ "," [color] ["," b[f]] ]

draw a line or a box on the current window, "b": A box is drawn, "bf": a filled box is drawn.
If option STEP is set, coordinates are relative.

=== LOCATE

Syntax:

    LOCATE [ row ] [ "," col ]

move cursor to col / row

=== POS()

Syntax:

    POS "(" expression ")"

returns the column of the cursor in the current window (expression given is a dummy value for
compatibility reasons, usually 0).

=== PRINT

Syntax:

    PRINT  [ expression ( [ ";" | "," ] expression )* ]

print the listed expressions to the screen. ";" means no space, "," means skip to next 9 col tab,
";" or "," at the end of the line mean no newline is printed.

=== PSET

Syntax:

    PSET [ STEP ] "(" x "," y ")" [ "," color ]

set a point in the window

=== WINDOW

Syntax:

    WINDOW id [ "," [ title ] [ "," [ "(" x1 "," y1 ")" "-" "(" x2 "," y2 ")" ] [ "," [type] [ "," screen-id ]]]]

Create and activate a new window, make it the new output window.

.Table type flags
|===
|Flag Name |Value | Description

|AW_FLAG_SIZE
|1
|window can be resized

|AW_FLAG_DRAG
|2
|window can be dragged

|AW_FLAG_DEPTH
|4
|window has depth widgets

|AW_FLAG_CLOSE
|8
|window can be closed

|AW_FLAG_REFRESH
|16
|auto refresh
|===

