= AQB Reference
Guenter Bartsch <guenter@zamia.org>
v0.1, 2020-07-12
:toc:

== Core Language

=== ASSERT

Syntax:

    ASSERT expr

raise an error message including line number information if the given expression evaluates to FALSE.

=== ACOS()

Syntax:

    ACOS "(" a ")"

obtain the arccosine of the floating point number

=== ASIN()

Syntax:

    ASIN "(" a ")"

obtain the arcsine of the floating point number

=== ATN()

Syntax:

    ATN "(" a ")"

obtain the arctangent of the floating point number

=== CAST()

Syntax:

    CAST "(" typedesc "," expr ")

casts an expression to a different data type

=== CHR$()

Syntax:

    CHR$ "(" expr ")"

returns a string containing the single character associated with the given character code

=== CONST

Syntax A:

    [ PUBLIC | PRIVATE ] CONST id1 [AS type] "=" expr [ "," id2 [AS type] "=" expr [ "," ...]]

Syntax B:

    [ PUBLIC | PRIVATE ] CONST AS type id1 "=" expr [ "," id2 "=" expr [ "," ...]]

declare constants

=== COS()

Syntax:

    COS "(" a ")"

obtain the cosine of the floating point number

=== DATA

Syntax:

    DATA literal ( "," literal )*

add values to the data section of the program. Those values can be later READ by the program at runtime.

=== DEFINT

Syntax:

    DEFINT letter [ "-" letter ] ( "," letter [ "-" letter ] )*

define all variables with names starting with the specified letter (or letter range) as INTEGER

=== DEFLNG

Syntax:

    DEFLNG letter [ "-" letter ] ( "," letter [ "-" letter ] )*

define all variables with names starting with the specified letter (or letter range) as LONG

=== DEFSNG

Syntax:

    DEFSNG letter [ "-" letter ] ( "," letter [ "-" letter ] )*

define all variables with names starting with the specified letter (or letter range) as SINGLE

=== DEFSTR

Syntax:

    DEFSTR letter [ "-" letter ] ( "," letter [ "-" letter ] )*

define all variables with names starting with the specified letter (or letter range) as STRING

=== DIM

Syntax A:

    [ PUBLIC | PRIVATE ] DIM [ SHARED ] var1 [ "(" arrayDimensions ")" ] AS type [ "=" expr ] [ "," var2 ...]

Syntax B:

    [ PUBLIC | PRIVATE ] DIM [ SHARED ] AS type var1 [ "(" arrayDimensions ")" ] [ "=" expr ] [ "," var2 ... ]

declare variables

Examples:

    DIM f AS SINGLE                          : REM traditional QBasic Syntax
    DIM SHARED g AS UBYTE                    : REM shared variable

    DIM AS ULONG l1, l2                      : REM declare multiple variables of the same type

    DIM AS INTEGER a (9, 1)                  : REM 2D dynamic array
    DIM AS INTEGER b (STATIC 9, 1)           : REM 2D static, C-like array

    DIM p AS INTEGER PTR                     : REM pointer

    DIM fp AS FUNCTION (INTEGER) AS INTEGER  : REM function pointer

static arrays are much faster than dynamic arrays but offer no runtime bounds checking

=== END

Syntax:

    END

exit the program (same as SYSTEM)

=== ERASE

Syntax:

    ERASE arrayName [ "," arrayName2 ...]

Free the allocated memory for each dynamic array listed.

=== ERROR

Syntax:

    ERROR n

raise error code n, exits the program unless a corresponding handler is registered using the ON ERROR ... statement

=== EXIT

Syntax:

    EXIT ( SUB | FUNCTION | DO | FOR | WHILE | SELECT ) [ "," ( SUB | ... ) ... ]

exits a DO, WHILE or FOR loop, a FUNCTION or a SUB procedure, or a SELECT statement.

=== EXP()

Syntax:

    EXP "(" a ")"

obtain the exponential of the floating point number

=== FOR ... NEXT

Syntax:

    FOR id [ AS type ] "=" expr TO expr [ STEP expr ]
        <code>
    NEXT [ id1 [ "," id2 [ "," ...] ] ]

counter loop using specified start and stop numerical boundaries, default increment is 1

=== FREE()

Syntax:

    FREE "(" x ")"

.Table x values
|===
|Value | Description

|-2
|stack size

|-1
|chip + fast mem

|0
|chip mem

|1
|fast mem

|2
|largest chip mem

|3
|largest fast mem

|===

=== GOTO

Syntax:

    GOTO ( num | ident )

jump a line label or a line number in the program

=== GOSUB

Syntax:

    GOSUB ( num | ident )

jump to a subroutine at line label or a line number in the program

=== IF ... THEN

Syntax A:

    IF expr ( GOTO ( numLiteral | ident ) [ ( ELSE numLiteral | Statement* ) ]
            | THEN ( numLiteral | Statement*) [ ( ELSE numLiteral | Statement* ) ]
            )
Syntax B:

    IF expr THEN
        <code>
    ( ELSEIF expr THEN
        <code> )*
    [ ELSE
        <code> ]
    ( END IF | ENDIF )

executes a statement or statement block depending on specified conditions.

=== IMPORT

Syntax:

    IMPORT id

import a module

=== LBOUND()

Syntax:

    LBOUND "(" array [ "," dimension ] ")"

Return the lower bound for the given array dimension.

=== LOG()

Syntax:

    LOG "(" l ")"

obtain the natural logarithm of the floating point number

=== OPTION EXPLICIT

Syntax:

    OPTION EXPLICIT [ ( ON | OFF ) ]

instructs the compiler to require variable declaration

=== OPTION PRIVATE

Syntax:

    OPTION PRIVATE [ ( ON | OFF ) ]

make declared variables, types, functions and subprograms private (not exported) by default

=== PEEK()

Syntax:

    PEEK "(" address ")"

return a byte from memory at the specified address

=== PEEKW()

Syntax:

    PEEKW "(" address ")"

return a word (16 bits) from memory at the specified address

=== PEEKL()

Syntax:

    PEEK "(" address ")"

return a long (32 bits) from memory at the specified address

=== POKE

Syntax:

    POKE address, value

store byte value at the specified memory address

=== POKEW

Syntax:

    POKEW address, value

store word (16 bits) value at the specified memory address

=== POKEL

Syntax:

    POKEL address, value

store long (32 bits) value at the specified memory address

=== READ

Syntax:

    READ varDesignator ( "," varDesignator )*

read values from the DATA section and assign them to one or more variables

=== REDIM

Syntax:

    REDIM [PRESERVE] [SHARED] arrayId ([[lbound TO] ubound [ "," ...]]) [ AS datatype ] [, ...]

declare or resize a dynamic array. Previous values are erased unless the PRESERVE keyword is specified.

=== RETURN

Syntax:

    RETURN [ expr ]

return from a subroutine or function. In case of return from a function, expr specifies the return value

=== SIN()

Syntax:

    SIN "(" a ")

obtain the sine of the floating point number

=== SIZEOF()

Syntax:

    SIZEOF "(" ident ")

Returns the memory size in bytes of a given variable or named type

=== SQR()

Syntax:

    SQR "(" x ")"

obtain the square root of the floating point number

=== STATIC

Syntax A:

    STATIC Identifier AS TypeIdentifier [ "(" arrayDimensions ")" ] [ "=" expr] ( "," Indetifier2 AS ... )*

Syntax B:

    STATIC AS TypeIdentifier [ "(" arrayDimensions ")" ] Identifier [ "=" expr] ( "," Identifier2 ... )*

declare variable(s) as static.

=== STR$()

Syntax:

    STR$ "(" expr ")"

return a string representation (the same one that is used in PRINT output) of a given numeric expression

=== SYSTEM

Syntax:

    SYSTEM

exit the program (same as END)

=== TAN()

Syntax:

    TAN "(" a ")"

obtain the tangent of the floating point number

=== TIMER()

Syntax:

    TIMER "(" ")"

returns the number of seconds past the previous midnite as a SINGLE float value

=== TYPE (UDT alias)

Syntax:

    TYPE ident AS typedesc [ "(" arrayDimensions ")" ]

Example:

    TYPE a_t AS INTEGER (STATIC 9)

declares a new named UDT

=== TYPE (UDT record)

Syntax:

    TYPE ident

      [PRIVATE:|PUBLIC:|PROTECTED:]
      var [ "(" arrayDimensions ")" ] AS typedesc
      AS typedesc var [ "(" arrayDimensions ")" ]
      DECLARE (SUB|FUNCTION|CONSTRUCTOR) ...
      ...

    END TYPE

declares a new record UDT

=== UBOUND()

Syntax:

    UBOUND "(" array [ "," dimension ] ")"

Return the upper bound for the given array dimension.

=== VARPTR()

Syntax:

    VARPTR "(" designator ")"

returns the address of a variable

=== WHILE ... WEND

Syntax:

    WHILE expression
        <code>
    WEND

repeat loop body while expression evaluates to TRUE

== AQB / AmigaBASIC

=== AREA

Syntax:

    AREA [STEP] (x, y)

add a point to an area to be filled

=== AREAFILL

Syntax:

    AREAFILL [mode]

fill a polygon defined by AREA statements, mode: 0=regular fill, 1=inverted fill

=== AREA OUTLINE

Syntax:

    AREA OUTLINE ( TRUE | FALSE )

enable or disable drawing of AREA polygon outlines

=== COLOR

Syntax:

    COLOR [ fg ] ["," [bg] ["," o]]

set foreground, background and or area outline pen

=== CSRLIN()

Syntax:

    CSRLIN "(" ")"

returns the current text row position

=== INKEY$()

Syntax:

    INKEY$ "(" ")"

returns a character entered from the keyboard

=== LINE

Syntax:

    LINE [[STEP] "(" x1 "," y1 ")" ] "-" [STEP] "(" x2 "," y2 ")" [ "," [color] ["," b[f]] ]

draw a line or a box on the current window, "b": A box is drawn, "bf": a filled box is drawn.
If option STEP is set, coordinates are relative.

=== LOCATE

Syntax:

    LOCATE [ row ] [ "," col ]

move cursor to col / row

=== PALETTE

Syntax:

    PALETTE n, red, green, blue

change the color palette entry for pen number n. The red, green and blue arguments are
be floating point values in the 0.0 ... 1.0 range.

=== PATTERN

Syntax:

    PATTERN [ lineptrn ] [ "," areaptrn ]

change pattern used to draw lines and areas.

    * lineptrn: 16 bit integer that defines the pattern for lines
    * areaptrn: array of 16 bit integers, number of elements must be a power of 2 (1, 2, 4, 8, ...)

=== POS()

Syntax:

    POS "(" expression ")"

returns the column of the cursor in the current window (expression given is a dummy value for
compatibility reasons, usually 0).

=== PRINT

Syntax:

    PRINT  [ expression ( [ ";" | "," ] expression )* ]

print the listed expressions to the screen. ";" means no space, "," means skip to next 9 col tab,
";" or "," at the end of the line mean no newline is printed.

=== PSET

Syntax:

    PSET [ STEP ] "(" x "," y ")" [ "," color ]

set a point in the window

=== SCREEN

Syntax:

    SCREEN screen-id, width, height, depth, mode [, title]

create a new screen

=== SCREEN CLOSE

Syntax:

    SCREEN CLOSE id

close screen indicated by id

.Table mode
|===
|Flag Name |Value | Description

|AS_MODE_LORES
|1
|LORES

|AS_MODE_HIRES
|2
|HIRES

|AS_MODE_LORES_LACED
|3
|LORES INTERLACED

|AS_MODE_HIRES_LACED
|4
|HIRES INTERLACED

|AS_MODE_HAM
|5
|LORES HAM

|AS_MODE_EXTRAHALFBRITE
|6
|LORES EXTRA HALFBRITE

|AS_MODE_HAM_LACED
|7
|LORES HAM INTERLACED

|AS_MODE_EXTRAHALFBRITE_LACED
|8
|LORES EXTRA HALFBRITE INTERLACED
|===

=== WINDOW

Syntax:

    WINDOW id [ "," [ title ] [ "," [ "(" x1 "," y1 ")" "-" "(" x2 "," y2 ")" ] [ "," [type] [ "," screen-id ]]]]

Create and activate a new window, make it the new output window.

=== WINDOW CLOSE

Syntax:

    WINDOW CLOSE id

close window indicated by id.

=== WINDOW OUTPUT

Syntax:

    WINDOW OUTPUT id

make window indicated by id the current output window.

.Table type flags
|===
|Flag Name |Value | Description

|AW_FLAG_SIZE
|1
|window can be resized

|AW_FLAG_DRAG
|2
|window can be dragged

|AW_FLAG_DEPTH
|4
|window has depth widgets

|AW_FLAG_CLOSE
|8
|window can be closed

|AW_FLAG_REFRESH
|16
|auto refresh

|AW_FLAG_BACKGROP
|32
|create a backdrop window

|AW_FLAG_BORDERLESS
|64
|make window borderless
|===

=== WINDOW()

Syntax:

    WINDOW "(" n ")"

return information about a window

.Table n
|===
|n | Description

|0
|current active window id

|1
|current output window id

|2
|current output window width

|3
|current output window height

|4
|current output cursor X

|5
|current output cursor Y

|6
|highest color index

|7
|pointer to current intuition output window

|8
|pointer to current rastport

|9
|output file handle

|10
|foreground pen

|11
|background pen

|12
|text width

|13
|text height

|14
|input file handle
|===

