= AQB Reference
Guenter Bartsch <guenter@zamia.org>
v0.1, 2020-07-12
:toc:

== Core Language

=== ASSERT

Syntax:

    ASSERT expr

raise an error message including line number information if the given expression evaluates to FALSE.

=== ACOS()

Syntax:

    ACOS "(" a ")"

obtain the arccosine of the floating point number

=== ASIN()

Syntax:

    ASIN "(" a ")"

obtain the arcsine of the floating point number

=== ATN()

Syntax:

    ATN "(" a ")"

obtain the arctangent of the floating point number

=== CAST()

Syntax:

    CAST "(" typedesc "," expr ")

casts an expression to a different data type

=== CHR$()

Syntax:

    CHR$ "(" expr ")"

returns a string containing the single character associated with the given character code

=== CONST

Syntax A:

    [ PUBLIC | PRIVATE ] CONST id1 [AS type] "=" expr [ "," id2 [AS type] "=" expr [ "," ...]]

Syntax B:

    [ PUBLIC | PRIVATE ] CONST AS type id1 "=" expr [ "," id2 "=" expr [ "," ...]]

declare constants

=== COS()

Syntax:

    COS "(" a ")"

obtain the cosine of the floating point number

=== DEFINT

Syntax:

    DEFINT letter [ "-" letter ] ( "," letter [ "-" letter ] )*

define all variables with names starting with the specified letter (or letter range) as INTEGER

=== DEFLNG

Syntax:

    DEFLNG letter [ "-" letter ] ( "," letter [ "-" letter ] )*

define all variables with names starting with the specified letter (or letter range) as LONG

=== DEFSNG

Syntax:

    DEFSNG letter [ "-" letter ] ( "," letter [ "-" letter ] )*

define all variables with names starting with the specified letter (or letter range) as SINGLE

=== DEFSTR

Syntax:

    DEFSTR letter [ "-" letter ] ( "," letter [ "-" letter ] )*

define all variables with names starting with the specified letter (or letter range) as STRING

=== DIM

Syntax A:

    [ PUBLIC | PRIVATE ] DIM [ SHARED ] var1 AS type [ "=" expr ] [ "," var2 AS ...]

Syntax B:

    [ PUBLIC | PRIVATE ] DIM [ SHARED ] AS type var1 [ "=" expr ] [ "," var2 ... ]

declare variables

=== END

Syntax:

    END

exit the program (same as SYSTEM)

=== ERROR

Syntax:

    ERROR n

raise error code n, exits the program unless a corresponding handler is registered using the ON ERROR ... statement

=== EXIT

Syntax:

    EXIT ( SUB | FUNCTION | DO | FOR | WHILE | SELECT ) [ "," ( SUB | ... ) ... ]

exits a DO, WHILE or FOR loop, a FUNCTION or a SUB procedure, or a SELECT statement.

=== EXP()

Syntax:

    EXP "(" a ")"

obtain the exponential of the floating point number

=== FOR ... NEXT

Syntax:

    FOR id [ AS type ] "=" expr TO expr [ STEP expr ]
        <code>
    NEXT [ id1 [ "," id2 [ "," ...] ] ]

counter loop using specified start and stop numerical boundaries, default increment is 1

=== FREE()

Syntax:

    FREE "(" x ")"

.Table x values
|===
|Value | Description

|-2
|stack size

|-1
|chip + fast mem

|0
|chip mem

|1
|fast mem

|2
|largest chip mem

|3
|largest fast mem

|===

=== GOTO

Syntax:

    GOTO ( num | ident )

jump a line label or a line number in the program

=== IF ... THEN

Syntax A:

    IF expr ( GOTO ( numLiteral | ident ) [ ( ELSE numLiteral | Statement* ) ]
            | THEN ( numLiteral | Statement*) [ ( ELSE numLiteral | Statement* ) ]
            )
Syntax B:

    IF expr THEN
        <code>
    ( ELSEIF expr THEN
        <code> )*
    [ ELSE
        <code> ]
    ( END IF | ENDIF )

executes a statement or statement block depending on specified conditions.

=== IMPORT

Syntax:

    IMPORT id

import a module

=== LOG()

Syntax:

    LOG "(" l ")"

obtain the natural logarithm of the floating point number

=== OPTION EXPLICIT

Syntax:

    OPTION EXPLICIT [ ( ON | OFF ) ]

instructs the compiler to require variable declaration

=== OPTION PRIVATE

Syntax:

    OPTION PRIVATE [ ( ON | OFF ) ]

make declared variables, types, functions and subprograms private (not exported) by default

=== SIN()

Syntax:

    SIN "(" a ")

obtain the sine of the floating point number

=== SIZEOF()

Syntax:

    SIZEOF "(" ident ")

Returns the memory size in bytes of a given variable or named type

=== SQR()

Syntax:

    SQR "(" x ")"

obtain the square root of the floating point number

=== STATIC

Syntax A:

    STATIC Identifier AS TypeIdentifier [ "(" arrayDimensions ")" ] [ "=" expr] ( "," Indetifier2 AS ... )*

Syntax B:

    STATIC AS TypeIdentifier [ "(" arrayDimensions ")" ] Identifier [ "=" expr] ( "," Identifier2 ... )*

declare variable(s) as static.

=== STR$()

Syntax:

    STR$ "(" expr ")"

return a string representation (the same one that is used in PRINT output) of a given numeric expression

=== SYSTEM

Syntax:

    SYSTEM

exit the program (same as END)

=== TAN()

Syntax:

    TAN "(" a ")"

obtain the tangent of the floating point number

=== WHILE ... WEND

Syntax:

    WHILE expression
        <code>
    WEND

repeat loop body while expression evaluates to TRUE

== AQB / AmigaBASIC

=== COLOR

Syntax:

    COLOR [ fg ] ["," bg]

set foreground and/or background pen

=== CSRLIN()

Syntax:

    CSRLIN "(" ")"

returns the current text row position

=== INKEY$()

Syntax:

    INKEY$ "(" ")"

returns a character entered from the keyboard

=== LINE

Syntax:

    LINE [[STEP] "(" x1 "," y1 ")" ] "-" [STEP] "(" x2 "," y2 ")" [ "," [color] ["," b[f]] ]

draw a line or a box on the current window, "b": A box is drawn, "bf": a filled box is drawn.
If option STEP is set, coordinates are relative.

=== LOCATE

Syntax:

    LOCATE [ row ] [ "," col ]

move cursor to col / row

=== PALETTE

Syntax:

    PALETTE n, red, green, blue

change the color palette entry for pen number n. The red, green and blue arguments are
be floating point values in the 0.0 ... 1.0 range.

=== POS()

Syntax:

    POS "(" expression ")"

returns the column of the cursor in the current window (expression given is a dummy value for
compatibility reasons, usually 0).

=== PRINT

Syntax:

    PRINT  [ expression ( [ ";" | "," ] expression )* ]

print the listed expressions to the screen. ";" means no space, "," means skip to next 9 col tab,
";" or "," at the end of the line mean no newline is printed.

=== PSET

Syntax:

    PSET [ STEP ] "(" x "," y ")" [ "," color ]

set a point in the window

=== SCREEN

Syntax:

    SCREEN screen-id, width, height, depth, mode [, title]

create a new screen

.Table mode
|===
|Flag Name |Value | Description

|AS_MODE_LORES
|1
|LORES

|AS_MODE_HIRES
|2
|HIRES

|AS_MODE_LORES_LACED
|3
|LORES INTERLACED

|AS_MODE_HIRES_LACED
|4
|HIRES INTERLACED

|AS_MODE_HAM
|5
|LORES HAM

|AS_MODE_EXTRAHALFBRITE
|6
|LORES EXTRA HALFBRITE

|AS_MODE_HAM_LACED
|7
|LORES HAM INTERLACED

|AS_MODE_EXTRAHALFBRITE_LACED
|8
|LORES EXTRA HALFBRITE INTERLACED
|===


=== WINDOW

Syntax:

    WINDOW id [ "," [ title ] [ "," [ "(" x1 "," y1 ")" "-" "(" x2 "," y2 ")" ] [ "," [type] [ "," screen-id ]]]]

Create and activate a new window, make it the new output window.

.Table type flags
|===
|Flag Name |Value | Description

|AW_FLAG_SIZE
|1
|window can be resized

|AW_FLAG_DRAG
|2
|window can be dragged

|AW_FLAG_DEPTH
|4
|window has depth widgets

|AW_FLAG_CLOSE
|8
|window can be closed

|AW_FLAG_REFRESH
|16
|auto refresh
|===

