= AQB Reference
Guenter Bartsch <guenter@zamia.org>
v0.1, 2020-07-12
:toc:

== Core Language

=== ASSERT

Syntax:

    ASSERT expr

raise an error message including line number information if the given expression evaluates to FALSE.

=== CAST()

Syntax:

    CAST "(" typedesc "," expr ")

casts an expression to a different data type

=== CHR$()

Syntax:

    CHR$ "(" expr ")"

returns a string containing the single character associated with the given character code

=== SIZEOF()

Syntax:

    SIZEOF "(" ident ")

Returns the memory size in bytes of a given variable or named type

=== STATIC

Syntax A:

    STATIC Identifier AS TypeIdentifier [ "(" arrayDimensions ")" ] [ "=" expr] ( "," Indetifier2 AS ... )*

Syntax B:

    STATIC AS TypeIdentifier [ "(" arrayDimensions ")" ] Identifier [ "=" expr] ( "," Identifier2 ... )*

declare variable(s) as static.

=== STR$()

Syntax:

    STR$ "(" expr ")"

return a string representation (the same one that is used in PRINT output) of a given numeric expression

=== WHILE ... WEND

Syntax:

    WHILE expression
        <code>
    WEND

repeat loop body while expression evaluates to TRUE

== AQB / AmigaBASIC

=== CSRLIN()

Syntax:

    CSRLIN "(" ")"

returns the current text row position

=== INKEY$()

Syntax:

    INKEY$ "(" ")"

returns a character entered from the keyboard

=== LOCATE

Syntax:

    LOCATE [ row ] [ "," col ]

move cursor to col / row

=== OPTION EXPLICIT

Syntax:

    OPTION EXPLICIT [ ( ON | OFF ) ]

instructs the compiler to require variable declaration

=== OPTION PRIVATE

Syntax:

    OPTION PRIVATE [ ( ON | OFF ) ]

make declared variables, types, functions and subprograms private (not exported) by default

=== POS()

Syntax:

    POS "(" expression ")"

returns the column of the cursor in the current window (expression given is a dummy value for
compatibility reasons, usually 0).

=== PRINT

Syntax:

    PRINT  [ expression ( [ ";" | "," ] expression )* ]

print the listed expressions to the screen. ";" means no space, "," means skip to next 9 col tab,
";" or "," at the end of the line mean no newline is printed.

=== PSET

Syntax:

    PSET [ STEP ] "(" x "," y ")" [ "," color ]

set a point in the window

=== WINDOW

Syntax:

    WINDOW id [ "," [ title ] [ "," [ "(" x1 "," y1 ")" "-" "(" x2 "," y2 ")" ] [ "," [type] [ "," screen-id ]]]]

Create and activate a new window, make it the new output window.

.Table type flags
|===
|Flag Name |Value | Description

|AW_FLAG_SIZE
|1
|window can be resized

|AW_FLAG_DRAG
|2
|window can be dragged

|AW_FLAG_DEPTH
|4
|window has depth widgets

|AW_FLAG_CLOSE
|8
|window can be closed

|AW_FLAG_REFRESH
|16
|auto refresh
|===

