= AQB Reference
Guenter Bartsch <guenter@zamia.org>
v0.1, 2020-07-12
:toc:

== Core Language

=== CAST()

Syntax:

    CAST "(" typedesc "," expr ")

casts an expression to a different data type

=== CHR$()

Syntax:

    CHR$ "(" expr ")"

returns a string containing the single character associated with the given character code

=== SIZEOF()

Syntax:

    SIZEOF "(" ident ")

Returns the memory size in bytes of a given variable or named type

=== STATIC

Syntax A:

    STATIC Identifier AS TypeIdentifier [ "(" arrayDimensions ")" ] [ "=" expr] ( "," Indetifier2 AS ... )*

Syntax B:

    STATIC AS TypeIdentifier [ "(" arrayDimensions ")" ] Identifier [ "=" expr] ( "," Identifier2 ... )*

declare variable(s) as static.

=== STR$()

Syntax:

    STR$ "(" expr ")"

return a string representation (the same one that is used in PRINT output) of a given numeric expression

=== WHILE ... WEND

Syntax:

    WHILE expression
        <code>
    WEND

repeat loop body while expression evaluates to TRUE

== AQB / AmigaBASIC



