OPTION EXPLICIT
OPTION PRIVATE

PUBLIC CLASS CArrayList IMPLEMENTS IList, ICloneable

    PUBLIC:

        DECLARE EXTERN CONSTRUCTOR (BYVAL capacity AS LONG = 0)

        DECLARE EXTERN VIRTUAL PROPERTY Count AS LONG

        DECLARE EXTERN VIRTUAL PROPERTY Capacity AS LONG
        DECLARE EXTERN VIRTUAL PROPERTY Capacity (BYVAL c AS LONG)

        DECLARE EXTERN VIRTUAL FUNCTION GetAt (BYVAL index AS LONG) AS ANY
        DECLARE EXTERN VIRTUAL SUB      SetAt (BYVAL index AS LONG, BYVAL obj AS ANY)

        DECLARE EXTERN VIRTUAL FUNCTION GetEnumerator () AS IEnumerator PTR

        DECLARE EXTERN VIRTUAL FUNCTION Clone () AS CObject PTR

        DECLARE EXTERN VIRTUAL FUNCTION Add (BYVAL obj AS ANY) AS LONG

        DECLARE EXTERN VIRTUAL FUNCTION Contains (BYVAL value AS ANY) AS BOOLEAN

        DECLARE EXTERN VIRTUAL PROPERTY IsReadOnly AS BOOLEAN

        DECLARE EXTERN VIRTUAL PROPERTY IsFixedSize AS BOOLEAN

        DECLARE EXTERN VIRTUAL FUNCTION IndexOf (BYVAL value AS ANY, BYVAL startIndex AS LONG=0, BYVAL count AS LONG=-1) AS LONG

        DECLARE EXTERN VIRTUAL SUB Insert (BYVAL index AS LONG, BYVAL value AS ANY)

        DECLARE EXTERN VIRTUAL SUB Remove (BYVAL value AS ANY)

        DECLARE EXTERN VIRTUAL SUB RemoveAt (BYVAL index AS LONG)

        DECLARE EXTERN VIRTUAL SUB RemoveAll

    PRIVATE:

		AS ANY PTR    _items
        AS LONG       _size
        AS LONG       _capacity

END CLASS

PUBLIC CLASS CArrayListEnumerator IMPLEMENTS IEnumerator

    PUBLIC:

        DECLARE EXTERN CONSTRUCTOR (BYVAL list AS CArrayList PTR)

        DECLARE EXTERN VIRTUAL FUNCTION MoveNext() AS BOOLEAN
        DECLARE EXTERN VIRTUAL PROPERTY Current AS ANY
        DECLARE EXTERN VIRTUAL SUB      Reset()

    PRIVATE:

        AS CArrayList PTR _list
        AS LONG           _index
        AS ANY            _currentElement

END CLASS



