.PHONY: clean all demo bench dev

all: demo bench dev

demo:
	cd demo ; make all

bench:
	cd bench ; make all

dev:
	cd dev ; make all

clean:
	cd demo ; make clean
	cd bench ; make clean
	cd dev ; make clean
