.PHONY: clean all compiler lib amigasupport commonrt

all: amigasupport compiler lib commonrt

amigasupport:
	cd amigasupport ; make all

compiler:
	cd compiler ; make all

lib:
	cd lib ; make all

commonrt:
	cd commonrt ; make all

clean:
	cd amigasupport ; make clean
	cd compiler ; make clean
	cd lib ; make clean
	cd commonrt ; make clean
