.PHONY: clean all compiler lib amigasupport

all: amigasupport compiler lib

amigasupport:
	cd amigasupport ; make all

compiler:
	cd compiler ; make all

lib:
	cd lib ; make all

clean:
	cd amigasupport ; make clean
	cd compiler ; make clean
	cd lib ; make clean
