
.PHONY: clean all runner printfloat dumpfonts rtgblit areaptrn gctest loadfont

all:	runner printfloat dumpfonts rtgblit areaptrn gctest loadfont

runner:
	cd runner ; make all

printfloat:
	cd printfloat ; make all

dumpfonts:
	cd dumpfonts ; make all

rtgblit:
	cd rtgblit ; make all

loadfont:
	cd loadfont ; make all

areaptrn:
	cd areaptrn ; make all

gctest:
	cd gctest ; make all

clean:
	cd ffputils ; make clean
	cd runner ; make clean
	cd printfloat ; make clean
	cd dumpfonts ; make clean
	cd rtgblit ; make clean
	cd areaptrn ; make clean
	cd gctest ; make clean
	cd loadfont ; make clean

