
.PHONY: clean all runner printfloat dumpfonts rtgblit areaptrn gctest loadfont

all:	runner printfloat dumpfonts rtgblit areaptrn gctest loadfont

runner:
	make -C $@ all

printfloat:
	make -C $@ all

dumpfonts:
	make -C $@ all

rtgblit:
	make -C $@ all

loadfont:
	make -C $@ all

areaptrn:
	make -C $@ all

gctest:
	make -C $@ all

clean:
	make -C ffputils clean
	make -C runner clean
	make -C printfloat clean
	make -C dumpfonts clean
	make -C rtgblit clean
	make -C areaptrn clean
	make -C gctest clean
	make -C loadfont clean
